mainPage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'mainPage'

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("callback/", views.callback, name="callback"),
    path('signup/', views.signup, name='signup'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

personalProject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainPage.urls')),
    path('', include('produtos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

produtos/urls.py
from django.urls import path

from . import views

app_name = 'produtos'

urlpatterns = [
    path("vender", views.vender, name="vender"),
]

mainPage/models.py
from django.db import models

class Utilizadores(models.Model):
    nome = models.CharField(max_length=100)
    nickname = models.CharField(max_length=50)
    email = models.CharField(max_length=100)

    # META CLASS
    class Meta:
        verbose_name = 'Utilizadores'
        verbose_name_plural = 'Utilizadores'

    def __str__(self):
        return self.nome

produtos/models.py
from django.db import models

# Create your models here.

mainPage/views.py
import json
from authlib.integrations.django_client import OAuth
from django.conf import settings
from django.shortcuts import redirect, render, redirect
from django.urls import reverse
from urllib.parse import quote_plus, urlencode

oauth = OAuth()

oauth.register(
    "auth0",
    client_id=settings.AUTH0_CLIENT_ID,
    client_secret=settings.AUTH0_CLIENT_SECRET,
    client_kwargs={
        "scope": "openid profile email",
    },
    server_metadata_url=f"https://{settings.AUTH0_DOMAIN}/.well-known/openid-configuration",
)

def login(request):
    return oauth.auth0.authorize_redirect(
        request, request.build_absolute_uri(reverse("mainPage:callback"))
    )

def callback(request):
    token = oauth.auth0.authorize_access_token(request)
    request.session["user"] = token
    return redirect(request.build_absolute_uri(reverse("mainPage:index")))

def logout(request):
    request.session.clear()

    return redirect(
        f"https://{settings.AUTH0_DOMAIN}/v2/logout?"
        + urlencode(
            {
                "returnTo": request.build_absolute_uri(reverse("mainPage:index")),
                "client_id": settings.AUTH0_CLIENT_ID,
            },
            quote_via=quote_plus,
        ),
    )

def index(request):
    return render(
        request,
        "index.html",
        context={
            "session": request.session.get("user"),
            "pretty": json.dumps(request.session.get("user"), indent=4),
        },
    )

def home(request):
    # user = User.objects.create_user("john", "lennon@thebeatles.com", "johnpassword")
    # user.save()

    return render(request, 'home.html')

'''
def login(request):
    
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        ...
    else:
        # Return an 'invalid login' error message.
        ...
    
    return render(request, 'login.html')
'''

def signup(request):
    return render(request, 'signup.html')

produtos/views.py
from django.shortcuts import render

def vender(request):
    return render(request, 'venderProdutos.html')

mainPage/templates/home.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


{% block body_title %}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src='{% static "reusableLogo.png" %}' width="38" height="38">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                <!--
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                </form>
                -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainPage:login' %}" style="color: #76D7C4">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">/</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainPage:signup' %}" style="color: #76D7C4">Sign Up</a>
                </li>
                <!--
                <li class="nav-item dropdown">
                    <a class="nav-link navbar-toggler-icon" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                -->
            </ul>
        </div>
    </div>
</nav>

<style>
    .center {
    display: block;
    max-width: 50%;
    max-height: 50%;
    margin-left: auto;
    margin-right: auto;
    }

    html, body {
    height: 100%;
    margin:0;
    padding:0;
    }

    cont {
    position:relative;
    height: 100%;
    width:100%;
    }

    cont imag {
    position:absolute;
    top:0;
    left:0;
    right:0;
    bottom:0;
    margin:auto;
    }

</style>

{% endblock %}

{% block body_content %}

    <!-- Imagem logotipo da empresa -->
    <cont>
        <imag src='{% static "online-shopping-ecommerce.png" %}' class="center">
    </cont>


{% endblock %}

{% block javascript %}
<script>
</script>
{% endblock %}

mainPage/templates/index.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


{% block body_title %}

<title>Reusable</title>
<link rel="icon" type="image/png" href="{% static 'reusableLogo.png' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>

    .navbar {
      height: 48px;
    }

    .center {
    display: block;
    max-width: 50%;
    max-height: 50%;
    margin-left: auto;
    margin-right: auto;
    }

    .btn-info, .btn-info:hover, .btn-info:active, .btn-info:visited {
    background-color: #76D7C4 !important;
    }

    img {
    max-width: 100%;
    height: auto;
    }

    .bg-img {
    /* The image used */
    background-image: url('{% static "online-shopping-ecommerce2.png" %}');
    min-height: 100%;

    /* Center and scale the image nicely */
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;

    /* Needed to position the navbar */
    position: relative;
    }

    .navbar-default.nav-top ul {
    display: inline-block;
    float: right;
    }

</style>
{% endblock %}

{% block body_content %}
<div class="bg-img">
    <!-- Navigation -->
<<<<<<< Updated upstream
    <nav class="navbar navbar-expand-lg navbar-dark bg-light static-top navbar-collapse border-bottom"
         style="z-index: 999">
=======
    <nav class="navbar navbar-expand-lg navbar-dark bg-light static-top navbar-collapse border-bottom" style="z-index: 999; height: 50px">
>>>>>>> Stashed changes
        <div class="container-fluid">
            <a class="navbar-brand" style="margin-right: 50px;" href="#">
                <img src='{% static "reusableLogo.png" %}' width="38" height="38">
            </a>
            <ul class="navbar-nav ms-auto">
                {% if session %}
                <li class="nav-item">
                    <a class="nav-link" style="color: black">Olá {{session.userinfo.nickname}}</a>
                </li>
                <li class="nav-item dropdown" style="padding-left: 10px;">
                    <a class="nav-link fa fa-bell-o" style="font-size:22px;; color: black" id="notification"
                       role="button"
                       data-bs-toggle="dropdown"></a>
                    <ul class="dropdown-menu dropdown-menu-end" style="text-align: center"
                        aria-labelledby="message">
                        <li class="dropdown-item">Notification 1</li>
                        <li class="dropdown-item">Notification 2</li>
                        <li class="dropdown-item">Notification 3</li>
                        <li class="dropdown-item">Notification 4</li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown" style="padding-left: 10px;">
                    <a class="nav-link fa fa-envelope-o" style="font-size:22px; color: black" id="message"
                       role="button"
                       data-bs-toggle="dropdown"></a>
                    <ul class="dropdown-menu dropdown-menu-end" style="text-align: center"
                        aria-labelledby="message">
                        <li class="dropdown-item">Message 1</li>
                        <li class="dropdown-item">Message 2</li>
                        <li class="dropdown-item">Message 3</li>
                        <li class="dropdown-item">Message 4</li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item" style="padding-left: 20px;">
                    <a class="nav-link btn btn-info btn-sm" style="color: black" href="{% url 'produtos:vender' %}">
                        Vender agora
                    </a>
                </li>
                <li class="nav-item dropdown" style="padding-left: 25px; padding-right: 15px">
                    <a class="nav-link fa fa-bars" style="color: black; font-size: 25px;" href="#"
                       id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'mainPage:logout' %}">Logout</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainPage:login' %}" style="color: #76D7C4">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <nav class="navbar navbar-expand-lg navbar-dark bg-light static-top navbar-collapse border-top"
         style="opacity: 80%; height: 50px">
        <div class="container-fluid">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainPage:login' %}"
                       style="color: #4682B4; font-size: 20px"><b>Homem</b></a>
                </li>
                <li class="nav-item" style="padding-left: 50px;">
                    <a class="nav-link" href="{% url 'mainPage:login' %}"
                       style="color: #4682B4; font-size: 20px"><b>Mulher</b></a>
                </li>
                <li class="nav-item" style="padding-left: 50px;">
                    <a class="nav-link" href="{% url 'mainPage:login' %}"
                       style="color: #4682B4; font-size: 20px"><b>Criança</b></a>
                </li>
            </ul>
        </div>
    </nav>
</div>
{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function () {
        const botao = document.getElementById('box');

        botao.addEventListener('mouseout', function handleMouseOut() {
            botao.style.color = 'black';
        });
    }

</script>
{% endblock %}

mainPage/templates/login.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


{% block body_title %}

<!-- Imagem logotipo da empresa -->
<img src='{% static "reusable.png" %}' width="220px">
<style>
</style>
{% endblock %}

{% block body_content %}
<div class="container-md" style="background-color: #76D7C4">
    <form method="POST" class="rounded col-xl-5 col-lg-6 col-md-8 col-sm-20 mx-auto form p-4"
          style="background-image: url('{% static " fundo.jpg
    " %}'); opacity: 80%; width: 40%"
    action={% url 'mainPage:home' %}>
    {% csrf_token %}
    <div class="text-center mt-2"><h1><b style="color: black">SIGN UP</b></h1></div>
    <div class="form-group col-md-12">
        <label for="exampleInputEmail1"><h6><b style="color: black">Username</b></h6></label>
        <input type="text" name="username" class="form-control mt-n2" id="exampleInputEmail1"
               aria-describedby="emailHelp"
               placeholder="User name">
    </div>
    <div class="form-group col-md-12">
        <label for="exampleInputPassword1"><h6><b style="color: black">Password</b></h6></label>
        <input type="password" name="password1" class="form-control mt-n2" id="exampleInputPassword1"
               placeholder="Password">
    </div>
    <div class="form-group col-md-12">
        <label for="exampleInputPassword1"><h6><b style="color: black ">Confirm password</b></h6></label>
        <input type="password" name="password2" class="form-control mt-n2" id="exampleInputPassword1"
               placeholder="Confirm Password">
    </div>
    <div class="text-center">
        <br/>
        <button type="submit" class="btn btn-secondary">Submit</button>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script>
</script>
{% endblock %}

mainPage/templates/signup.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}


{% block body_title %}

<!-- Imagem logotipo da empresa -->
<img src='{% static "reusable.png" %}' width="220px">
<style>
</style>
{% endblock %}

{% block body_content %}
<div class="container">
  <ul class="nav bg-info">
    <li class="nav-item">
      <a class="nav-link link-light" href="/">HOME</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="/members">MEMBERS</a>
    </li>
  </ul>

  {% block content %}
  {% endblock %}
</div>
{% endblock %}

{% block javascript %}
<script>
</script>
{% endblock %}

produtos/templates/venderProdutos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <p>Under Construction</p>
</body>
</html>